---
- name: Deploy config to R1 (Arista EOS)
  hosts: R1
  tasks:
    - name: Upload config for R1
      arista.eos.eos_config:
        src: configs/R1.cfg
- name: Deploy config to R2 (Cisco Nexus)
  hosts: R2
  tasks:
    - name: Upload config for R2
      cisco.nxos.nxos_config:
        src: configs/R2.cfg
- name: Deploy config to R3 (Juniper Junos Evolved)
  hosts: R3
  tasks:
    - name: Upload config for R3
      junipernetworks.junos.junos_config:
        src: configs/R3.cfg
